### ISSUE TITLE
Contribution Guideline.

### ISSUE THREAD

**Issue by shekohex** [garethwarry/chimera#1]
Hi , I'm Interesting in this Project so I was thinking is there is a Contribution Guideline or a Road Map , so that I can contribute ?
And another Question , What Version of **CO** should I use for Development ?
Thanks.

**Comment by garethwarry** [comment]
Hi shekohex! Thanks for your interest; I wasn't really expecting contributors for this project yet. Things on this project are still changing very often, but I'll be releasing an open source project soon that will be ready for contributors. I'll keep this issue open and let you know when this project has more of a plan. In the meantime, keep a look out on the community forum for the new release.

**Comment by shekohex** [comment]
I waiting, Thanks Gareth.
I love the comments in the base , it's explains every thing.. Pretty much :+1: 
Great Job

**Comment by garethwarry** [comment]
Thank you very much. I hope you'll find the same in the new base I'm authoring as well. I put a lot of work into it so far, but it's finally gaining traction. I'll make sure to make a contributors guide for when I open it. And that source will target 5187. Thanks for your feedback.

**Comment by shekohex** [comment]
i this project still maintained ?

**Comment by garethwarry** [comment]
No. This project is public only because Microsoft canceled my academic account with Github. It's on hiatus until I complete other work, and then it will likely only be private. I don't recommend using this version due to some bad styling I did with the code while learning Go. Once the new project is on Gitlab, which is a dotnet core project, I'll close this issue. I appreciate your willingness to participate, but that help will be much better placed on the community project I'm working on rather than my personal project.

**Comment by garethwarry** [comment]
And just for additional clarification,
Chimera = personal project (go)
Comet = community project (dotnet core)

**Comment by shekohex** [comment]
Oh ok.
for that, just when you going to release the `Comet` project, drop the link here.
or even better, we could work on it together, if it is going to be open sourced anyway.

**Comment by garethwarry** [comment]
I appreciate the offer, and I will take you up on it - but the reason why I started the community project was to teach myself a few technologies. I'll let you know when it's ready, and I'll definitely post a link here for you. Again, thanks for your interest.

**Comment by ice-j** [comment]
I'm up for the Comet project too :)

**Comment by garethwarry** [comment]
https://gitlab.com/spirited/comet
