### ISSUE TITLE
DISCUSSION : NPC Server, and A Scripting Language

### ISSUE THREAD

**Issue by shekohex** [garethwarry/chimera#2]
Hay :smile:  , I was Wondering How will NPC Server Work ?
and is it will use any scripting language with Go ? like [golua](https://github.com/aarzilli/golua) or [gofer-lua](https://github.com/yuin/gopher-lua) .
or something like that ?
I mean , to make it easy to add new NPC's and it's dialogs, data, information ..etc
I think it will be easier than adding it in code !
or making it in a database like 5095 Binary version .. oh man it was Awful :tired_face: 
any way , I can't wait to release it :smile:

**Comment by garethwarry** [comment]
Hi shekohex, I plan on using Lua. If you'd like to discuss the source, then feel free to continue on the community thread for Chimera. I would be happy to discuss further. Best Regards.

**Comment by shekohex** [comment]
Can you share the link of this thread please
Thanks again.

**Comment by shekohex** [comment]
Ok ,I found it.
